export const WEBSITE_CATEGORIES = [
  { label: "E-commerce", value: "ecommerce" },
  { label: "Business", value: "business" },
  { label: "Portfolio", value: "portfolio" },
  { label: "Blog", value: "blog" },
  { label: "News & Media", value: "news_media" },
  { label: "Educational", value: "educational" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Social Networking", value: "social_networking" },
  { label: "Government & Public Services", value: "government" },
  { label: "Nonprofit & Charity", value: "nonprofit" },
  { label: "Forum & Community", value: "forum_community" },
  { label: "Healthcare & Medical", value: "healthcare" },
  { label: "Technology & SaaS", value: "technology_saas" },
  { label: "Landing Page", value: "landing_page" },
  { label: "Real Estate", value: "real_estate" },
  { label: "Travel & Tourism", value: "travel_tourism" },
  { label: "Finance & Banking", value: "finance_banking" },
  { label: "Job Portal", value: "job_portal" },
  { label: "Personal Website", value: "personal" },
];
